name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Lint markdown"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Get the list of changed markdown files
      - name: Calculate changed markdown files
        uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          files: "**/*.md"
          separator: ","

      - name: Lint changed markdown files
        uses: DavidAnson/markdownlint-cli2-action@v19
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          config: ./.markdownlint.json
          globs: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ","
